// Code generated by protoc-gen-gologfields. DO NOT EDIT.

package logfields

func (m *LogField) LogFields() map[string]string {
	return map[string]string{}
}

func (m *LogField) ExtractRequestFields(dst map[string]interface{}) {
	// Handle being called on nil message.
	if m == nil {
		return
	}
}
