// Copyright (c) Improbable Worlds Ltd, All Rights Reserved

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: logfields.proto

package logfields

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name of the log context field where the value of this field should be
	// recorded. Fields with empty names are ignored.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *LogField) Reset() {
	*x = LogField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logfields_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogField) ProtoMessage() {}

func (x *LogField) ProtoReflect() protoreflect.Message {
	mi := &file_logfields_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogField.ProtoReflect.Descriptor instead.
func (*LogField) Descriptor() ([]byte, []int) {
	return file_logfields_proto_rawDescGZIP(), []int{0}
}

func (x *LogField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var file_logfields_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*LogField)(nil),
		Field:         62132,
		Name:          "improbable.logfield",
		Tag:           "bytes,62132,opt,name=logfield",
		Filename:      "logfields.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// logfield indicates if and how the annotated field should be included as
	// context in log messages. This applies when a log message is generated
	// while processing a proto message that contains the field (directly or via
	// an embedded message).
	//
	// optional improbable.LogField logfield = 62132;
	E_Logfield = &file_logfields_proto_extTypes[0]
)

var File_logfields_proto protoreflect.FileDescriptor

var file_logfields_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x6f, 0x67, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x69, 0x6d, 0x70, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x6c, 0x65, 0x1a, 0x20, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x1e, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x3a,
	0x51, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1d, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xb4, 0xe5, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x6d, 0x70, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x6c, 0x65, 0x2e,
	0x4c, 0x6f, 0x67, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6e, 0x76, 0x78, 0x2f, 0x67, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x6c, 0x6f,
	0x67, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x3b, 0x6c, 0x6f, 0x67, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_logfields_proto_rawDescOnce sync.Once
	file_logfields_proto_rawDescData = file_logfields_proto_rawDesc
)

func file_logfields_proto_rawDescGZIP() []byte {
	file_logfields_proto_rawDescOnce.Do(func() {
		file_logfields_proto_rawDescData = protoimpl.X.CompressGZIP(file_logfields_proto_rawDescData)
	})
	return file_logfields_proto_rawDescData
}

var file_logfields_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_logfields_proto_goTypes = []interface{}{
	(*LogField)(nil),                  // 0: improbable.LogField
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_logfields_proto_depIdxs = []int32{
	1, // 0: improbable.logfield:extendee -> google.protobuf.FieldOptions
	0, // 1: improbable.logfield:type_name -> improbable.LogField
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_logfields_proto_init() }
func file_logfields_proto_init() {
	if File_logfields_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_logfields_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_logfields_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_logfields_proto_goTypes,
		DependencyIndexes: file_logfields_proto_depIdxs,
		MessageInfos:      file_logfields_proto_msgTypes,
		ExtensionInfos:    file_logfields_proto_extTypes,
	}.Build()
	File_logfields_proto = out.File
	file_logfields_proto_rawDesc = nil
	file_logfields_proto_goTypes = nil
	file_logfields_proto_depIdxs = nil
}
